# Generated by Django 5.0 on 2023-12-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_listings_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
