# Generated by Django 5.0 on 2023-12-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_listings_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
