# Generated by Django 5.0 on 2023-12-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_watchlist_auction_watchlist_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='description',
            field=models.CharField(max_length=128),
        ),
    ]
