# Generated by Django 5.0 on 2023-12-14 19:27

import auctions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auction_listings_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
