# Generated by Django 5.0 on 2023-12-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_bids_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='close_status',
            field=models.BooleanField(default=False),
        ),
    ]
