# Generated by Django 5.0 on 2023-12-14 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_auction_listings_create_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='create_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='auction_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
