# Generated by Django 5.0 on 2023-12-15 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_comments_auction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=256)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='auctions.auction_listings')),
            ],
        ),
    ]
